### ISSUE TITLE
minion: Implement a hard timeout for all tests

### ISSUE THREAD

**Issue by sajal** [turbobytes/pulse#33]
Some tests (example #5) can run forever. This makes CNC think minion is unresponsive and kicks it out. 

We need to implement some hard timeout such that no matter what the minion will reply to CNC, and cancel the test within the specified time-frame.

**Comment by coolparadox** [comment]
I'd like to tackle this one.

If I understand correctly, the hard timeout is supposed to be a minion feature, ie there are no changes in CNC.

Any suggestion for a proper hard timeout value? Should we have distinct hard timeouts for each test type?

**Comment by coolparadox** [comment]
Hi @sajal 

In preparing test types for honoring a hard timeout, I extended ``CurlImpl()`` and ``DNSImpl()`` with a Context parameter, so they promptly return if context deadline is exceeded. See: [TestCurlWithTimeout](/turbobytes/pulse/blob/6e4b34dea58532ff24e457e2b44c99668806678f/utils/curl_test.go#L96), [TestDNSImplWithTimeout](/turbobytes/pulse/blob/6e4b34dea58532ff24e457e2b44c99668806678f/utils/dns_test.go#L118).

As for ``MtrImpl()``, would you be willing to accept a patch to your ``mtrparser`` that adds a Context parameter to [ExecuteMTR()](/sajal/mtrparser/blob/e285743e904b3fd30ba57bbfb6b7edf75dd7758d/mtr.go#L250) and replaces ``exec.Command()`` calls by ``exec.CommandContext()``? This is the most straightforward way of making ``MtrImpl()`` deadline aware IMO.

**Comment by coolparadox** [comment]
Note: 3c98fd0 relies on sajal/mtrparser#2 to be accepted.

**Comment by coolparadox** [comment]
Branch ``hard_timeout`` enforces a hard timeout of 50 seconds to all test types executed by minions. This happens through context deadlines, that allows test resources to be gracefully released if the hard timeout is reached.

There is a simple test case to each test type that checks if a microssecond hard timeout is being honored (ie, causes _"context deadline exceeded"_ error).

----

What's left: a friendly translation for hard timeout error. I see this error as a severe one, as under normal circumstances test's regular timeouts are supposed to be in place and the hard timeout will never be reached.

I propose a translation somewhere around: _"Test was cancelled because agent was unresponsible for ``<hard threshold>`` seconds during test execution. This may indicate agent is malfunctioning; please inform maintainers."_
